using System;
using System.Data.SqlClient;
using System.IO;
using System.Linq;

namespace MoleSql
{
    /// <summary>
    /// Represents a data context for the MoleSQL ORM framework.
    /// </summary>
    public sealed class MoleSqlDataContext : IDisposable
    {
        readonly SqlConnection connection;
        readonly MoleSqlQueryProvider provider;
        readonly bool disposeConnection;

        bool disposed;

        /// <summary>
        /// Gets or sets a <see cref="TextWriter"/> that receives the SQL queries generated by the
        /// underlying query provider.
        /// </summary>
        public TextWriter Log
        {
            get => provider.Log;
            set => provider.Log = value;
        }

        /// <summary>
        /// Creates a new <see cref="MoleSqlDataContext"/> for the specified connection.
        /// </summary>
        /// <param name="connectionString">A connection string defining the SQL server connection to use.</param>
        public MoleSqlDataContext(string connectionString)
        {
            disposeConnection = true;
            connection = new SqlConnection(connectionString);
            provider = new MoleSqlQueryProvider(this.connection);
        }

        /// <summary>
        /// Creates a new <see cref="MoleSqlDataContext"/> for the given <see cref="SqlConnection"/>.
        /// </summary>
        /// <param name="connection">The <see cref="SqlConnection"/> to use with this context.</param>
        /// <exception cref="ArgumentNullException"><paramref name="connection"/> was <code>null</code>.</exception>
        public MoleSqlDataContext(SqlConnection connection)
        {
            this.connection = connection ?? throw new ArgumentNullException(nameof(connection));
            provider = new MoleSqlQueryProvider(this.connection);
        }

        /// <summary>
        /// Creates a query to the specified table.
        /// </summary>
        /// <typeparam name="T">The table to query.</typeparam>
        /// <returns>An <see cref="IQueryable{T}"/> representing a query to the table specified by <typeparamref name="T"/>.</returns>
        public IQueryable<T> GetTable<T>()
        {
            CheckDisposed();
            return new Query<T>(provider);
        }

        /// <inheritdoc />
        public void Dispose()
        {
            if (disposeConnection)
                connection.Dispose();
            disposed = true;
        }

        void CheckDisposed()
        {
            if (disposed) throw new ObjectDisposedException(nameof(MoleSqlDataContext));
        }
    }
}
