//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoleSql.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MoleSql.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The aggregate type &apos;{0}&apos; is not supported. ähnelt.
        /// </summary>
        internal static string Exception_AggregateTypeNotSupported {
            get {
                return ResourceManager.GetString("Exception_AggregateTypeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot apply operator &apos;{0}&apos; to NULL values. ähnelt.
        /// </summary>
        internal static string Exception_BinaryExpressionCannotBeAppliedToNullValues {
            get {
                return ResourceManager.GetString("Exception_BinaryExpressionCannotBeAppliedToNullValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The binary operator &apos;{0}&apos; is not supported. ähnelt.
        /// </summary>
        internal static string Exception_BinaryExpressionIsNotSupported {
            get {
                return ResourceManager.GetString("Exception_BinaryExpressionIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The result set contains multiple columns and cannot be converted to &apos;{0}&apos;. ähnelt.
        /// </summary>
        internal static string Exception_CannotBeCreatedFromMultipleColumns {
            get {
                return ResourceManager.GetString("Exception_CannotBeCreatedFromMultipleColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A result set can only be iterated once (in &apos;{0}&apos;). ähnelt.
        /// </summary>
        internal static string Exception_CanOnlyBeIteratedOnce {
            get {
                return ResourceManager.GetString("Exception_CanOnlyBeIteratedOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The method &apos;{0}&apos; only supports queries based on &apos;{1}&apos;. ähnelt.
        /// </summary>
        internal static string Exception_DoesNotSupportDifferentQueryProvider {
            get {
                return ResourceManager.GetString("Exception_DoesNotSupportDifferentQueryProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The expression of type &apos;{0}&apos; (node type &apos;{1}&apos;) is not a sequence. ähnelt.
        /// </summary>
        internal static string Exception_ExpressionIsNotASequence {
            get {
                return ResourceManager.GetString("Exception_ExpressionIsNotASequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The join type &apos;{0}&apos; is not supported. ähnelt.
        /// </summary>
        internal static string Exception_JoinTypeIsNotSupported {
            get {
                return ResourceManager.GetString("Exception_JoinTypeIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Asynchronous aggregators like &apos;{0}&apos; can only appear on top of the expression tree. ähnelt.
        /// </summary>
        internal static string Exception_MethodCanOnlyAppearOnTopOfExpressionTree {
            get {
                return ResourceManager.GetString("Exception_MethodCanOnlyAppearOnTopOfExpressionTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The method &apos;{0}&apos; is not supported. ähnelt.
        /// </summary>
        internal static string Exception_MethodNotSupported {
            get {
                return ResourceManager.GetString("Exception_MethodNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The expression node type &apos;{0}&apos; is invalid at this point. ähnelt.
        /// </summary>
        internal static string Exception_NodeTypeIsInvalid {
            get {
                return ResourceManager.GetString("Exception_NodeTypeIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The expression node type &apos;{0}&apos; is not a valid type for a SELECT source. ähnelt.
        /// </summary>
        internal static string Exception_NodeTypeIsInvalidSelectSourceType {
            get {
                return ResourceManager.GetString("Exception_NodeTypeIsInvalidSelectSourceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot convert  a null reference to &apos;{0}&apos;. ähnelt.
        /// </summary>
        internal static string Exception_NullCannotBeCastToType {
            get {
                return ResourceManager.GetString("Exception_NullCannotBeCastToType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die NULL values are not supported on the left side of binary operands. ähnelt.
        /// </summary>
        internal static string Exception_NullValuesOnLeftSideNotSupported {
            get {
                return ResourceManager.GetString("Exception_NullValuesOnLeftSideNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The &apos;{0}&apos; instance has already been disposed. ähnelt.
        /// </summary>
        internal static string Exception_ObjectDisposed {
            get {
                return ResourceManager.GetString("Exception_ObjectDisposed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reference to undefined column. ähnelt.
        /// </summary>
        internal static string Exception_ReferenceToUndefinedColumn {
            get {
                return ResourceManager.GetString("Exception_ReferenceToUndefinedColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The unary operator &apos;{0}&apos; is not supported. ähnelt.
        /// </summary>
        internal static string Exception_UnaryExpressionIsNotSupported {
            get {
                return ResourceManager.GetString("Exception_UnaryExpressionIsNotSupported", resourceCulture);
            }
        }
    }
}
